apiVersion: v1
kind: Service
metadata:
  name: model
  labels:
    app: model
spec:
  selector:
    app: model
  type: NodePort
  ports:
    # FastAPI port
    - name: http
      port: 8000
      nodePort: 30100
      targetPort: 8000
      protocol: TCP
    # Prometheus metrics port
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
status:
  loadBalancer: {}
