apiVersion: v1
kind: Service
metadata:
  name: model
  labels:
    app: model
spec:
  selector:
    app: model
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30100
      protocol: TCP